---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crane-proxy
  namespace: openshift-migration
data:
  clusters: '[]'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: openshift-migration
  labels:
    app: crane
    service: proxy
spec:
  selector:
     matchLabels:
       app: crane
       service: proxy
  template:
    metadata:
      labels:
        app: crane
        service: proxy
    spec:
      containers:
        - name: proxy
          env:
          - name: GIN_MODE
            value: release
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: quay.io/konveyor/crane-reverse-proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      serviceAccountName: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: openshift-migration
  labels:
    app: crane
    service: proxy
spec:
  ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: crane
    service: proxy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  name: proxy
  namespace: openshift-migration
  labels:
    app: crane
    service: proxy
spec:
  to:
    kind: Service
    name: proxy
  port:
    targetPort: port-8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
